AllCops:
  NewCops: enable

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  CountAsOne: ['array', 'heredoc']
  AllowedMethods: ['describe']

Naming/VariableNumber:
  EnforcedStyle: snake_case

Style/Documentation:
  Enabled: false
